name: IPQ-LAI-sc脚本

on:
  schedule:
    # 北京时间周五0点 = UTC时间周四16:00
    - cron: '0 16 * * 4'
  workflow_dispatch:

permissions:
  contents: write

env:
  # 芯片变量（未来可扩展）
  CHIP: ipq60xx
  
  # 默认信息
  DEFAULT_IP: 192.168.111.1
  DEFAULT_USER: root
  DEFAULT_PASS: none
  DEFAULT_WIFI: 12345678
  AUTHOR: Mary

jobs:
  # 构建所有配置
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # 配置类型在前，仓库在后
        config_type: [Ultra, Max, Pro]
        repo: 
          - imm|${{ github.server_url }}/laipeng668/immortalwrt.git|master|immwrt
          - open|${{ github.server_url }}/laipeng668/openwrt.git|master|openwrt
          - lib|${{ github.server_url }}/laipeng668/openwrt-6.x.git|k6.12-nss|libwrt
      max-parallel: 3
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置仓库环境变量
        run: |
          set -e
          echo "=== 设置仓库环境变量 ==="
          IFS='|' read -r REPO_KEY REPO_URL REPO_BRANCH REPO_SHORT <<< "${{ matrix.repo }}"
          echo "REPO_URL=${REPO_URL}" >> $GITHUB_ENV
          echo "REPO_BRANCH=${REPO_BRANCH}" >> $GITHUB_ENV
          echo "REPO_SHORT=${REPO_SHORT}" >> $GITHUB_ENV
          echo "CONFIG_TYPE=${{ matrix.config_type }}" >> $GITHUB_ENV
          echo "仓库URL: ${REPO_URL}"
          echo "仓库分支: ${REPO_BRANCH}"
          echo "仓库简称: ${REPO_SHORT}"
          echo "配置类型: ${{ matrix.config_type }}"
          echo "=== 仓库环境变量设置完成 ==="
          
      - name: 初始化错误日志
        run: |
          set -e
          echo "=== 初始化错误日志 ==="
          mkdir -p logs
          echo "=== 构建开始: ${{ env.REPO_SHORT }}-${{ env.CHIP }}-${{ matrix.config_type }} ===" > logs/error.log
          echo "构建时间: $(date)" >> logs/error.log
          echo "=== 错误日志初始化完成 ==="
          
      - name: 清理工作目录
        run: |
          set -e
          echo "=== 清理工作目录 ==="
          rm -rf openwrt temp_config
          echo "工作目录清理完成"
          echo "=== 工作目录清理完成 ==="
          
      # 优化缓存策略 - 仅依赖基础配置
      - name: 缓存feeds目录（全矩阵通用）
        id: cache-feeds
        uses: actions/cache@v4
        with:
          path: openwrt/feeds
          key: feeds-${{ hashFiles('configs/${{ env.CHIP }}_base.config', 'configs/${{ env.REPO_SHORT }}_base.config') }}
          restore-keys: |
            feeds-
          
      - name: 缓存下载目录（全矩阵通用）
        id: cache-dl
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: dl-${{ hashFiles('configs/${{ env.CHIP }}_base.config', 'configs/${{ env.REPO_SHORT }}_base.config') }}
          restore-keys: |
            dl-
            
      - name: 缓存ccache（全矩阵通用）
        id: cache-ccache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ github.run_id }}
          restore-keys: |
            ccache-
            
      - name: 缓存工具链目录（全矩阵通用）
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: openwrt/build_dir/toolchain-*
          key: toolchain-${{ hashFiles('configs/${{ env.CHIP }}_base.config', 'configs/${{ env.REPO_SHORT }}_base.config') }}
          restore-keys: |
            toolchain-
            
      - name: 缓存staging目录（全矩阵通用）
        id: cache-staging
        uses: actions/cache@v4
        with:
          path: openwrt/staging_dir
          key: staging-${{ hashFiles('configs/${{ env.CHIP }}_base.config', 'configs/${{ env.REPO_SHORT }}_base.config') }}
          restore-keys: |
            staging-
          
      - name: 显示缓存状态
        run: |
          echo "=== 缓存状态 ==="
          echo "feeds缓存: ${{ steps.cache-feeds.outputs.cache-hit }}"
          echo "dl缓存: ${{ steps.cache-dl.outputs.cache-hit }}"
          echo "ccache缓存: ${{ steps.cache-ccache.outputs.cache-hit }}"
          echo "toolchain缓存: ${{ steps.cache-toolchain.outputs.cache-hit }}"
          echo "staging缓存: ${{ steps.cache-staging.outputs.cache-hit }}"
          echo "=== 缓存状态显示完成 ==="
          
      - name: 合并配置文件
        run: |
          set -e
          echo "=== 开始合并配置文件 ==="
          mkdir -p temp_config
          echo "合并基础配置: configs/${{ env.CHIP }}_base.config" >> logs/error.log
          cat configs/${{ env.CHIP }}_base.config > temp_config/.config
          echo "合并仓库配置: configs/${{ env.REPO_SHORT }}_base.config" >> logs/error.log
          cat configs/${{ env.REPO_SHORT }}_base.config >> temp_config/.config
          echo "合并类型配置: configs/${{ matrix.config_type }}.config" >> logs/error.log
          cat configs/${{ matrix.config_type }}.config >> temp_config/.config
          
          # 验证配置文件合并成功
          if [ ! -s temp_config/.config ]; then
            echo "错误：配置文件合并失败" >> logs/error.log
            exit 1
          fi
          
          # 调试信息
          echo "=== 配置文件内容片段 ===" >> logs/error.log
          grep -E "CONFIG_TARGET_DEVICE_" temp_config/.config >> logs/error.log
          echo "========================" >> logs/error.log
          echo "配置文件合并成功"
          echo "=== 配置文件合并完成 ==="
          
      - name: 提取设备信息
        run: |
          set -e
          echo "=== 开始提取设备信息 ==="
          DEVICE_LINES=$(grep '^CONFIG_TARGET_DEVICE_.*=y$' temp_config/.config)
          if [ -z "$DEVICE_LINES" ]; then
            echo "错误：配置文件中未找到启用的设备" >> logs/error.log
            exit 1
          fi
          
          DEVICE_NAMES=""
          for line in $DEVICE_LINES; do
            DEVICE_NAME=$(echo "$line" | sed -n 's/^CONFIG_TARGET_DEVICE_[^_]*_[^_]*_DEVICE_\([^=]*\)=y/\1/p')
            if [ -n "$DEVICE_NAME" ]; then
              DEVICE_NAMES="$DEVICE_NAMES $DEVICE_NAME"
            fi
          done
          
          DEVICE_COUNT=$(echo "$DEVICE_NAMES" | wc -w)
          if [ "$DEVICE_COUNT" -eq 0 ]; then
            echo "错误：无法从配置文件中提取设备名称" >> logs/error.log
            exit 1
          fi
          
          echo "DEVICE_NAMES=${DEVICE_NAMES}" >> $GITHUB_ENV
          echo "提取到的设备名称: $DEVICE_NAMES" >> logs/error.log
          echo "设备数量: $DEVICE_COUNT" >> logs/error.log
          echo "设备信息提取成功"
          echo "=== 设备信息提取完成 ==="
          
      - name: 检查系统依赖
        run: |
          set -e
          echo "=== 开始检查系统依赖 ==="
          echo "检查已安装的软件包..." >> logs/error.log
          dpkg -l | grep -E "build-essential|clang|flex|bison|g\+\+|gawk|gcc-multilib|g\+\+-multilib|gettext|git|libncurses5-dev|libssl-dev|python3-distutils|python3-setuptools|rsync|unzip|zlib1g-dev|file|wget" >> logs/error.log
          echo "检查编译工具..." >> logs/error.log
          which gcc g++ make git python3 >> logs/error.log
          gcc --version | head -1 >> logs/error.log
          g++ --version | head -1 >> logs/error.log
          make --version | head -1 >> logs/error.log
          git --version >> logs/error.log
          python3 --version >> logs/error.log
          echo "系统依赖检查完成"
          echo "=== 系统依赖检查完成 ==="
          
      - name: 克隆源码
        run: |
          set -e
          echo "=== 开始克隆源码 ==="
          echo "克隆仓库: ${{ env.REPO_URL }}" >> logs/error.log
          echo "克隆分支: ${{ env.REPO_BRANCH }}" >> logs/error.log
          git clone --depth 1 ${{ env.REPO_URL }} -b ${{ env.REPO_BRANCH }} openwrt 2>&1 | tee -a logs/error.log
          echo "源码克隆完成"
          echo "=== 源码克隆完成 ==="
          
      - name: 安装依赖
        run: |
          set -e
          echo "=== 开始安装依赖 ==="
          cd openwrt
          echo "更新软件包列表..." >> ../logs/error.log
          sudo apt-get update >> ../logs/error.log 2>&1
          echo "安装编译依赖..." >> ../logs/error.log
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils python3-setuptools rsync unzip zlib1g-dev file wget >> ../logs/error.log 2>&1
          echo "依赖安装完成"
          echo "=== 依赖安装完成 ==="
          
      # 新增步骤：执行自定义脚本
      - name: 执行自定义脚本
        run: |
          set -e
          echo "=== 开始执行自定义脚本 ==="
          cd openwrt
          echo "执行脚本: ../scripts/script.sh" >> ../logs/error.log
          chmod +x ../scripts/script.sh
          ../scripts/script.sh 2>&1 | tee -a ../logs/error.log
          echo "自定义脚本执行完成"
          echo "=== 自定义脚本执行完成 ==="
          
      - name: 编译固件
        run: |
          set -e
          echo "=== 开始编译固件 ==="
          cd openwrt
          
          # 应用配置
          echo "应用配置文件..." >> ../logs/error.log
          cp ../temp_config/.config .config
          
          # 添加缺失的内核配置选项
          echo "# CONFIG_NF_CONNTRACK_DSCPREMARK_EXT is not set" >> .config
          
          # 验证配置文件
          echo "验证配置文件..." >> ../logs/error.log
          grep -E "CONFIG_TARGET_DEVICE_|CONFIG_LINUX_KERNEL_VERSION|CONFIG_NF_CONNTRACK_DSCPREMARK_EXT" .config >> ../logs/error.log
          
          echo "运行defconfig..." >> ../logs/error.log
          make defconfig >> ../logs/error.log 2>&1
          
          # 再次确认新选项被禁用
          echo "# CONFIG_NF_CONNTRACK_DSCPREMARK_EXT is not set" >> .config
          
          # 启用ccache
          export CCACHE_DIR=~/.ccache
          export USE_CCACHE=1
          export CCACHE_COMPRESS=1
          
          # 编译
          echo "开始编译..." >> ../logs/error.log
          echo "使用 $(nproc) 个并行任务进行编译" >> ../logs/error.log
          
          # 尝试编译，捕获错误
          if ! make -j$(nproc) V=s 2>&1 | tee -a ../logs/error.log; then
            echo "错误：并行编译失败，尝试使用单线程重新编译..." >> ../logs/error.log
            if ! make -j1 V=sc 2>&1 | tee -a ../logs/error.log; then
              echo "错误：单线程编译也失败" >> ../logs/error.log
              echo "=== 最后2000行错误日志 ===" >> ../logs/error.log
              tail -n 2000 ../logs/error.log >> ../logs/error.log
              exit 1
            fi
          fi
          
          echo "编译完成"
          echo "=== 编译固件完成 ==="
          
      - name: 收集产物
        if: always()
        run: |
          set -e
          echo "=== 开始收集产物 ==="
          ARTIFACT_DIR="${{ env.REPO_SHORT }}-${{ matrix.config_type }}"
          FIRMWARE_DIR="${{ env.REPO_SHORT }}-${{ matrix.config_type }}-firmware"
          mkdir -p "$ARTIFACT_DIR"
          mkdir -p "$FIRMWARE_DIR"
          
          # 修改后的TARGET_DIR，支持多种架构
          TARGET_DIR="openwrt/bin/targets/${{ env.CHIP }}"
          
          # 添加调试信息
          echo "=== 检查目标目录 ===" >> logs/error.log
          ls -la "$TARGET_DIR" >> logs/error.log 2>&1 || echo "目标目录不存在: $TARGET_DIR" >> logs/error.log
          
          # 复制配置文件
          cp temp_config/.config "$ARTIFACT_DIR/${{ env.REPO_SHORT }}-${{ matrix.config_type }}.config"
          
          # 复制其他文件
          if [ -f "openwrt/.config.buildinfo" ]; then
            cp openwrt/.config.buildinfo "$ARTIFACT_DIR/${{ env.REPO_SHORT }}-${{ matrix.config_type }}.config.buildinfo"
          fi
          
          if [ -d "$TARGET_DIR" ] && [ -f "$TARGET_DIR"/*.manifest ]; then
            cp "$TARGET_DIR"/*.manifest "$ARTIFACT_DIR/${{ env.REPO_SHORT }}-${{ matrix.config_type }}.manifest"
          fi
          
          if [ -f "openwrt/build.log" ]; then
            cp openwrt/build.log "$ARTIFACT_DIR/${{ env.REPO_SHORT }}-${{ matrix.config_type }}-build.log"
          fi
          
          if [ -d "openwrt/bin/packages" ]; then
            mkdir -p "$ARTIFACT_DIR/packages"
            cp -r openwrt/bin/packages/* "$ARTIFACT_DIR/packages/"
          fi
          
          if [ -f logs/error.log ] && [ -s logs/error.log ]; then
            cp logs/error.log "$ARTIFACT_DIR/${{ env.REPO_SHORT }}-${{ matrix.config_type }}-error.log"
          fi
          
          # 处理固件文件 - 只处理包含"-squashfs-"的文件
          if [ -d "$TARGET_DIR" ]; then
            echo "=== 处理固件文件 ===" >> logs/error.log
            ls -la "$TARGET_DIR" >> logs/error.log
            
            FOUND_FIRMWARE=0
            
            for file in "$TARGET_DIR"/*.bin; do
              if [ -f "$file" ] && [[ "$file" == *"-squashfs-"* ]]; then
                FOUND_FIRMWARE=1
                echo "发现符合条件的固件文件: $(basename "$file")" >> logs/error.log
                
                # 从文件名提取设备名称
                DEVICE_NAME_FROM_FILE=$(basename "$file" | sed -n 's/^.*-\(.*\)-squashfs-.*\.bin$/\1/p')
                
                if [ -z "$DEVICE_NAME_FROM_FILE" ]; then
                  echo "警告：无法从文件名中提取设备名称: $(basename "$file")" >> logs/error.log
                  continue
                fi
                
                # 确定固件类型
                if [[ "$file" == *"factory"* ]]; then
                  FIRMWARE_TYPE="factory"
                elif [[ "$file" == *"sysupgrade"* ]]; then
                  FIRMWARE_TYPE="sysupgrade"
                else
                  continue
                fi
                
                NEW_NAME="${{ env.REPO_SHORT }}-${DEVICE_NAME_FROM_FILE}-${FIRMWARE_TYPE}-${{ matrix.config_type }}.bin"
                cp "$file" "$FIRMWARE_DIR/$NEW_NAME"
                echo "处理固件: $(basename "$file") -> $NEW_NAME" >> logs/error.log
              fi
            done
            
            if [ "$FOUND_FIRMWARE" -eq 0 ]; then
              echo "警告: 没有找到任何符合条件的固件文件（包含-squashfs-的.bin文件）" >> logs/error.log
              # 创建一个说明文件，避免上传错误
              echo "没有找到符合条件的固件文件（包含-squashfs-的.bin文件）" > "$FIRMWARE_DIR/no-firmware-found.txt"
            fi
          else
            echo "错误: 目标目录不存在: $TARGET_DIR" >> logs/error.log
            # 创建一个说明文件，避免上传错误
            echo "目标目录不存在: $TARGET_DIR" > "$FIRMWARE_DIR/target-directory-not-found.txt"
          fi
          
          echo "产物收集完成"
          echo "=== 产物收集完成 ==="
          
      - name: 上传错误日志
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs-${{ env.REPO_SHORT }}-${{ matrix.config_type }}
          path: |
            logs/error.log
          retention-days: 30
          if-no-files-found: warn
          
      - name: 上传产物
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_SHORT }}-${{ matrix.config_type }}
          path: |
            ${{ env.REPO_SHORT }}-${{ matrix.config_type }}/
          retention-days: 7
          if-no-files-found: warn
          
      - name: 上传固件
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPO_SHORT }}-${{ matrix.config_type }}-firmware
          path: |
            ${{ env.REPO_SHORT }}-${{ matrix.config_type }}-firmware/
          retention-days: 7
          if-no-files-found: error

  # 打包并发布Release
  package-and-release:
    needs: build
    runs-on: ubuntu-22.04
    if: always()
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 下载所有产物
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts/
          
      - name: 准备发布目录
        run: |
          set -e
          echo "=== 开始准备发布目录 ==="
          mkdir -p release/{config,log,app,firmware,assets}
          
          # 收集配置文件
          echo "收集配置文件..."
          find all-artifacts -name "*.config" -exec cp {} release/config/ \;
          find all-artifacts -name "*.config.buildinfo" -exec cp {} release/config/ \;
          find all-artifacts -name "*.manifest" -exec cp {} release/config/ \;
          
          # 收集日志文件
          echo "收集日志文件..."
          find all-artifacts -name "*-build.log" -exec cp {} release/log/ \;
          find all-artifacts -name "*-error.log" -exec cp {} release/log/ \;
          
          # 收集软件包
          echo "收集软件包..."
          find all-artifacts -name "packages" -type d -exec cp -r {} release/app/ \;
          
          # 收集固件文件
          echo "收集固件文件..."
          find all-artifacts -name "*.bin" -exec cp {} release/firmware/ \;
          
          # 打包文件
          echo "打包文件..."
          tar -czf release/${{ env.CHIP }}-config.tar.gz -C release/config .
          tar -czf release/${{ env.CHIP }}-log.tar.gz -C release/log .
          tar -czf release/${{ env.CHIP }}-app.tar.gz -C release/app .
          
          # 复制到assets目录
          cp release/${{ env.CHIP }}-config.tar.gz release/assets/
          cp release/${{ env.CHIP }}-log.tar.gz release/assets/
          cp release/${{ env.CHIP }}-app.tar.gz release/assets/
          cp release/firmware/*.bin release/assets/ 2>/dev/null || true
          
          # 提取信息
          KERNEL_VERSION=""
          LUCI_APPS=""
          DEVICE_LIST=""
          
          for config_file in release/config/*.config; do
            KERNEL_VER=$(grep "^CONFIG_LINUX_KERNEL_VERSION=" "$config_file" | cut -d'"' -f2)
            if [ -n "$KERNEL_VER" ]; then
              KERNEL_VERSION="$KERNEL_VER"
              break
            fi
          done
          
          if [ -d release/app ]; then
            LUCI_APPS=$(find release/app -name "luci-app-*.ipk" | sed 's/.*\///g' | sort | uniq | tr '\n' ' ')
          fi
          
          if [ -d release/firmware ]; then
            DEVICE_LIST=$(ls release/firmware/*.bin | sed -n 's/.*-\([^-]*\)-.*\.bin/\1/p' | sort | uniq | tr '\n' ' ')
          fi
          
          echo "KERNEL_VERSION=${KERNEL_VERSION}" >> $GITHUB_ENV
          echo "LUCI_APPS=${LUCI_APPS}" >> $GITHUB_ENV
          echo "DEVICE_LIST=${DEVICE_LIST}" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
          
          # 创建Release body文件
          cat > release/body.md << EOF
          默认管理地址：${{ env.DEFAULT_IP }}
          默认用户：${{ env.DEFAULT_USER }}
          默认密码：${{ env.DEFAULT_PASS }}
          默认WIFI密码: ${{ env.DEFAULT_WIFI }}
          
          固件包括（${{ env.CHIP }}）的设备：${{ env.DEVICE_LIST }}
          
          固件内核版本：${{ env.KERNEL_VERSION }}
          作者: ${{ env.AUTHOR }}
          发布时间: ${{ env.RELEASE_DATE }}
          编译的luci-app列表：${{ env.LUCI_APPS }}
          
          ## 下载说明
          - 固件文件：请从下面的附件中下载对应设备的固件文件
          - 配置文件：${{ env.CHIP }}-config.tar.gz
          - 编译日志：${{ env.CHIP }}-log.tar.gz
          - 软件包：${{ env.CHIP }}-app.tar.gz
          EOF
          
          echo "发布目录准备完成"
          echo "=== 发布目录准备完成 ==="
          
      - name: 创建Release并上传文件
        uses: softprops/action-gh-release@v1
        if: always()
        with:
          tag_name: ${{ env.RELEASE_DATE }}-${{ env.CHIP }}
          name: ${{ env.CHIP }} Release ${{ env.RELEASE_DATE }}
          body_path: release/body.md
          files: |
            release/assets/*
          draft: false
          prerelease: false
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
